version: "3.3"

services:
  article-service:
    image: backend-test:dev
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.26
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: articles
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  mock-external-server:
    image: rodolpheche/wiremock
    ports:
      - "8090:8080"
