server:
  port: 8080

external-service:
  base-url: http://external-service.com:8000

info:
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/articles?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
